//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationTable
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string SubTitle1 { get; set; }
        public string SubTitle2 { get; set; }
        public string GPA { get; set; }
        public string Date { get; set; }
    }
}
