//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCvProject.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfoTable> UserInfoTable { get; set; }
        public virtual DbSet<CertificateTable> CertificateTable { get; set; }
        public virtual DbSet<ContactTable> ContactTable { get; set; }
        public virtual DbSet<EducationTable> EducationTable { get; set; }
        public virtual DbSet<ExperienceTable> ExperienceTable { get; set; }
        public virtual DbSet<HobbyTable> HobbyTable { get; set; }
        public virtual DbSet<InformationTable> InformationTable { get; set; }
        public virtual DbSet<SkillsTable> SkillsTable { get; set; }
    }
}
